name: Security - Snyk Scan

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
      - 'sonar-project.properties'  # Ignora modifiche al file di config Sonar
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/workflows/**'
      - 'sonar-project.properties'
  workflow_dispatch:

jobs:
  snyk-scan:
    name: Snyk Security Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk & Reporter
        run: npm install -g snyk snyk-to-html

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Generazione Report
      - name: Snyk Test
        continue-on-error: true 
        run: |
          snyk test --all-projects --detect-subprojects --severity-threshold=critical --json > snyk_results.json

      - name: Convert Snyk JSON to HTML
        run: snyk-to-html -i snyk_results.json -o snyk_report.html

      - name: Upload Snyk HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Snyk-Security-Report
          path: snyk_report.html
